//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleEng { get; set; }
        public string Slug { get; set; }
        public string BlogImage_Default { get; set; }
        public string BlogImage_Square { get; set; }
        public string BlogImage_Option { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string DescriptionEng { get; set; }
        public string ContentEng { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsHomePage { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastEditedTime { get; set; }
        public int PictureId { get; set; }
        public int BlogCategoryId { get; set; }
        public int Position { get; set; }
    
        public virtual BlogCategory BlogCategory { get; set; }
    }
}
