//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OutsourcingDBEntities : DbContext
    {
        public OutsourcingDBEntities()
            : base("name=OutsourcingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BlogCategory> BlogCategories { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<ChanelData> ChanelDatas { get; set; }
        public virtual DbSet<DataUser> DataUsers { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<LogDiary> LogDiaries { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<ProductAttributeMapping> ProductAttributeMappings { get; set; }
        public virtual DbSet<ProductAttribute> ProductAttributes { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductPictureMapping> ProductPictureMappings { get; set; }
        public virtual DbSet<ProductRelationship> ProductRelationships { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SourceData> SourceDatas { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<UserDataMapping> UserDataMappings { get; set; }
        public virtual DbSet<WebsiteAttribute> WebsiteAttributes { get; set; }
    }
}
