//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPictureMapping
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsMainPicture { get; set; }
        public int ProductId { get; set; }
        public int PictureId { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual Product Product { get; set; }
    }
}
